
//------------------------------- USER
export const GET_USER_REQUEST = "GET_USER_REQUEST";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_FAILURE = "GET_USER_FAILURE";

export const GET_TOP_ACTIVE_USER_REQUEST = "GET_TOP_ACTIVE_USER_REQUEST";
export const GET_TOP_ACTIVE_USER_SUCCESS = "GET_TOP_ACTIVE_USER_SUCCESS";
export const GET_TOP_ACTIVE_USER_FAILURE = "GET_TOP_ACTIVE_USER_FAILURE";

export const POST_USER_REQUEST = "POST_USER_REQUEST";
export const POST_USER_SUCCESS = "POST_USER_SUCCESS";
export const POST_USER_FAILURE = "POST_USER_FAILURE";

export const DELETE_USER_REQUEST = "DELETE_USER_REQUEST";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_FAILURE = "DELETE_USER_FAILURE";

export const PUT_USER_REQUEST = "PUT_USER_REQUEST";
export const PUT_USER_SUCCESS = "PUT_USER_SUCCESS";
export const PUT_USER_FAILURE = "PUT_USER_FAILURE";

//---------------------------- POST

export const GET_POST_REQUEST = "GET_POST_REQUEST";
export const GET_POST_SUCCESS = "GET_POST_SUCCESS";
export const GET_POST_FAILURE = "GET_POST_FAILURE";

export const GET_TOP_POST_REQUEST = "GET_TOP_POST_REQUEST";
export const GET_TOP_POST_SUCCESS = "GET_TOP_POST_SUCCESS";
export const GET_TOP_POST_FAILURE = "GET_TOP_POST_FAILURE";

export const POST_POST_REQUEST = "POST_POSTE_REQUEST";
export const POST_POST_SUCCESS = "POST_POST_SUCCESS";
export const POST_POST_FAILURE = "POST_POST_FAILURE";

export const DELETE_POST_REQUEST = "DELETE_POST_REQUEST";
export const DELETE_POST_SUCCESS = "DELETE_POST_SUCCESS";
export const DELETE_POST_FAILURE = "DELETE_POST_FAILURE";

export const PUT_POST_REQUEST = "PUT_POST_REQUEST";
export const PUT_POST_SUCCESS = "PUT_POST_SUCCESS";
export const PUT_POST_FAILURE = "PUT_POST_FAILURE";
