export const GET_LOGIN_USER_REQUEST = "GET_LOGIN_USER_REQUEST";
export const GET_LOGIN_USER_SUCCESS = "GET_LOGIN_USER_SUCCESS";
export const GET_LOGIN_USER_FAILURE = "GET_LOGIN_USER_FAILURE";

export const GET_SIGNUP_USER_REQUEST = "GET_SIGNUP_USER_REQUEST";
export const GET_SIGNUP_USER_SUCCESS = "GET_SIGNUP_USER_SUCCESS";
export const GET_SIGNUP_USER_FAILURE = "GET_SIGNUP_USER_FAILURE";

export const LOGOUT_USER = "LOGOUT_USER";

